#!/bin/bash
set -eu

CONSUL_HOST="${CONSUL_HOST:-localhost}"
CONSUL_PORT="${CONSUL_PORT:-8500}"

CONSUL_ADDR="http://${CONSUL_HOST}:${CONSUL_PORT}"

usage() {
    echo "usage: ${0##*/} <task id> <period> <command> [arg1 ...]"
    exit 1
}

grab_lock_or_die() {
    local task_id="$1"
    local schedule_date="$2"
    hostname="$(curl -s ${CONSUL_ADDR}/v1/agent/self | jq -r .Config.NodeName)"
    ret="$(curl -s -X PUT -d "${hostname}" "${CONSUL_ADDR}/v1/kv/cronsul/${task_id}/${schedule_date}?cas=0")"
    if [[ "$ret" != "true" ]]; then
        exit
    fi
}

if [[ "$#" -lt 3 ]]; then
    usage
fi
task_id="$1"
period="$2"
command=("${@:3}")

# This will be wrong if cron starts our job really late.
schedule_date="$(( ($(date '+%s') / period) * period))"

grab_lock_or_die "$task_id" "$schedule_date"

"${command[@]}"
